/*
 * This source file was generated by the Gradle 'init' task
 */
package com.block20;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appTest() {
        // Basic test to ensure application classes compile
        assertTrue("App test passes", true);
    }
}
